import { VirtualFileSystem, PropDefinition, StateDefinition, MethodDefinition, JSXStructure } from './virtualFileSystem'

export interface BuilderContext {
  vfs: VirtualFileSystem
  currentComponent?: string
  errors: string[]
  warnings: string[]
}

export class ComponentBuilder {
  private context: BuilderContext

  constructor() {
    this.context = {
      vfs: new VirtualFileSystem(),
      errors: [],
      warnings: []
    }
  }

  // AI Function Tools - These will be called by the AI model

  /**
   * Create a new React component
   */
  createComponent(name: string, description?: string): void {
    try {
      if (!/^[A-Z][a-zA-Z0-9]*$/.test(name)) {
        throw new Error('Component name must start with uppercase letter and contain only alphanumeric characters')
      }

      this.context.vfs.createComponent(name)
      this.context.currentComponent = name

      // Create component file entry
      this.context.vfs.createFile(`${name}.jsx`, `// ${description || `${name} component`}\n// Generated by ComponentBuilder`, 'component')

    } catch (error) {
      this.context.errors.push(`createComponent(${name}): ${(error as any).message}`)
    }
  }

  /**
   * Add state to the current component
   */
  addState(name: string, initialValue: any, type: 'useState' | 'useRef' = 'useState'): void {
    try {
      if (!this.context.currentComponent) {
        throw new Error('No current component. Call createComponent() first.')
      }

      if (!/^[a-z][a-zA-Z0-9]*$/.test(name)) {
        throw new Error('State name must start with lowercase letter and contain only alphanumeric characters')
      }

      const stateDefinition: StateDefinition = {
        name,
        type,
        initialValue
      }

      this.context.vfs.addComponentState(this.context.currentComponent, stateDefinition)

    } catch (error) {
      this.context.errors.push(`addState(${name}): ${(error as any).message}`)
    }
  }

  /**
   * Add a method/function to the current component
   */
  addMethod(name: string, parameters: string[], body: string, isAsync: boolean = false): void {
    try {
      if (!this.context.currentComponent) {
        throw new Error('No current component. Call createComponent() first.')
      }

      if (!/^[a-z][a-zA-Z0-9]*$/.test(name)) {
        throw new Error('Method name must start with lowercase letter and contain only alphanumeric characters')
      }

      // Validate that body doesn't contain template literals
      if (body.includes('`') && body.includes('${')) {
        throw new Error('Method body cannot contain template literals. Use string concatenation instead.')
      }

      const method: MethodDefinition = {
        name,
        parameters,
        body,
        isAsync
      }

      this.context.vfs.addComponentMethod(this.context.currentComponent, method)

    } catch (error) {
      this.context.errors.push(`addMethod(${name}): ${(error as any).message}`)
    }
  }

  /**
   * Add props definition to the current component
   */
  addProp(name: string, type: PropDefinition['type'], required: boolean = false, defaultValue?: any): void {
    try {
      if (!this.context.currentComponent) {
        throw new Error('No current component. Call createComponent() first.')
      }

      if (!/^[a-z][a-zA-Z0-9]*$/.test(name)) {
        throw new Error('Prop name must start with lowercase letter and contain only alphanumeric characters')
      }

      const prop: PropDefinition = {
        name,
        type,
        required,
        defaultValue
      }

      this.context.vfs.addComponentProp(this.context.currentComponent, prop)

    } catch (error) {
      this.context.errors.push(`addProp(${name}): ${(error as any).message}`)
    }
  }

  /**
   * Set the JSX structure for the current component
   */
  setJSX(element: string, attributes?: Record<string, any>, children?: (string | JSXStructure)[], events?: Record<string, string>): void {
    try {
      if (!this.context.currentComponent) {
        throw new Error('No current component. Call createComponent() first.')
      }

      // Validate JSX element name
      if (!/^[a-z][a-zA-Z0-9]*$/.test(element) && !/^[A-Z][a-zA-Z0-9]*$/.test(element)) {
        throw new Error('JSX element must be valid HTML element or React component name')
      }

      // Validate event handlers don't use template literals
      if (events) {
        for (const [eventName, handler] of Object.entries(events)) {
          if (handler.includes('`') && handler.includes('${')) {
            throw new Error(`Event handler ${eventName} cannot contain template literals. Use string concatenation instead.`)
          }
        }
      }

      const jsx: JSXStructure = {
        element,
        attributes: attributes || {},
        children: children || [],
        events
      }

      this.context.vfs.setComponentJSX(this.context.currentComponent, jsx)

    } catch (error) {
      this.context.errors.push(`setJSX(${element}): ${(error as any).message}`)
    }
  }

  /**
   * Add CSS styles to a component
   */
  addStyles(componentName: string, css: string): void {
    try {
      const fileName = `${componentName}.module.css`

      // Validate CSS doesn't contain problematic syntax
      if (css.includes('`')) {
        this.context.warnings.push('CSS contains backticks which may cause issues')
      }

      this.context.vfs.createFile(fileName, css, 'style')

    } catch (error) {
      this.context.errors.push(`addStyles(${componentName}): ${(error as any).message}`)
    }
  }

  /**
   * Create a simple list item JSX structure
   */
  createListItem(text: string, onClick?: string): JSXStructure {
    const jsx: JSXStructure = {
      element: 'li',
      attributes: {
        style: 'padding: 8px; cursor: pointer; border-bottom: 1px solid #eee;'
      },
      children: [text]
    }

    if (onClick) {
      jsx.events = { onClick }
    }

    return jsx
  }

  /**
   * Create a button JSX structure
   */
  createButton(text: string, onClick: string): JSXStructure {
    return {
      element: 'button',
      attributes: {
        style: 'padding: 8px 16px; background-color: #007bff; color: white; border: none; border-radius: 4px; cursor: pointer;'
      },
      children: [text],
      events: { onClick }
    }
  }

  /**
   * Create an input JSX structure
   */
  createInput(type: string = 'text', placeholder?: string, value?: string, onChange?: string): JSXStructure {
    const jsx: JSXStructure = {
      element: 'input',
      attributes: {
        type,
        style: 'padding: 8px; border: 1px solid #ccc; border-radius: 4px; margin-right: 8px;'
      },
      children: []
    }

    if (placeholder) jsx.attributes.placeholder = placeholder
    if (value) jsx.attributes.value = value
    if (onChange) jsx.events = { onChange }

    return jsx
  }

  /**
   * Create a div container JSX structure
   */
  createContainer(children: (string | JSXStructure)[]): JSXStructure {
    return {
      element: 'div',
      attributes: {
        style: 'padding: 20px; font-family: Arial, sans-serif;'
      },
      children
    }
  }

  /**
   * Validate and compile all components
   */
  compile(): { success: boolean; files: Record<string, string>; errors: string[]; warnings: string[] } {
    const allErrors = [...this.context.errors]
    const allWarnings = [...this.context.warnings]

    // Validate all components
    for (const component of this.context.vfs.listFiles().filter(f => f.type === 'component')) {
      const componentName = component.path.replace('.jsx', '')
      const validation = this.context.vfs.validateComponent(componentName)

      allErrors.push(...validation.errors)
      allWarnings.push(...validation.warnings)
    }

    const success = allErrors.length === 0

    let files: Record<string, string> = {}

    if (success) {
      try {
        files = this.context.vfs.toArtifactFiles()
      } catch (error) {
        allErrors.push(`Compilation failed: ${(error as any).message}`)
        return { success: false, files: {}, errors: allErrors, warnings: allWarnings }
      }
    }

    return {
      success,
      files,
      errors: allErrors,
      warnings: allWarnings
    }
  }

  /**
   * Get current build status
   */
  getStatus(): { componentCount: number; errors: string[]; warnings: string[] } {
    return {
      componentCount: this.context.vfs.listFiles().filter(f => f.type === 'component').length,
      errors: this.context.errors,
      warnings: this.context.warnings
    }
  }

  /**
   * Reset the builder
   */
  reset(): void {
    this.context = {
      vfs: new VirtualFileSystem(),
      errors: [],
      warnings: []
    }
  }
}

// Export function-style interface for AI usage
export function createComponentBuilder(): ComponentBuilder {
  return new ComponentBuilder()
}

// Helper functions for common patterns
export const ComponentPatterns = {
  /**
   * Create a basic todo list structure
   */
  createTodoListComponent(builder: ComponentBuilder): void {
    builder.createComponent('TodoList', 'A simple todo list application')

    // Add state
    builder.addState('todos', [])
    builder.addState('newTodo', '')

    // Add methods
    builder.addMethod('addTodo', [], `
      if (newTodo.trim()) {
        setTodos([...todos, { id: Date.now(), text: newTodo, completed: false }])
        setNewTodo('')
      }
    `)

    builder.addMethod('deleteTodo', ['id'], `
      setTodos(todos.filter(function(todo) { return todo.id !== id }))
    `)

    builder.addMethod('toggleTodo', ['id'], `
      setTodos(todos.map(function(todo) {
        return todo.id === id ? { ...todo, completed: !todo.completed } : todo
      }))
    `)

    // Create JSX structure
    const todoItems: JSXStructure = {
      element: 'ul',
      attributes: { style: 'list-style: none; padding: 0;' },
      children: [
        `{todos.map(function(todo) {
          return React.createElement('li', {
            key: todo.id,
            style: {
              padding: '10px',
              borderBottom: '1px solid #eee',
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'center'
            }
          }, [
            React.createElement('span', {
              style: {
                textDecoration: todo.completed ? 'line-through' : 'none',
                cursor: 'pointer'
              },
              onClick: function() { toggleTodo(todo.id) }
            }, todo.text),
            React.createElement('button', {
              onClick: function() { deleteTodo(todo.id) },
              style: {
                background: '#ff4444',
                color: 'white',
                border: 'none',
                padding: '4px 8px',
                borderRadius: '4px',
                cursor: 'pointer'
              }
            }, 'Delete')
          ])
        })}`
      ]
    }

    const inputSection: JSXStructure = {
      element: 'div',
      attributes: { style: 'margin-bottom: 20px;' },
      children: [
        builder.createInput('text', 'Enter a new todo...', 'newTodo', 'function(e) { setNewTodo(e.target.value) }'),
        builder.createButton('Add Todo', 'addTodo')
      ]
    }

    const mainContainer = builder.createContainer([
      { element: 'h1', attributes: {}, children: ['Todo List'] },
      inputSection,
      todoItems
    ])

    builder.setJSX(mainContainer.element, mainContainer.attributes, mainContainer.children)
  }
}