#!/usr/bin/env tsx

/**
 * Live Demo: AI Agents System Working Locally
 * 
 * This demonstrates the key features with working examples
 */

import { 
  BaseAgent,
  AgentManager,
  DefaultAgentRegistry,
  ContextManager,
  AgentConfig,
  AgentContext,
  AgentResult,
  AIProvider
} from '../src';

// Enhanced Mock AI Provider
class LiveDemoAIProvider {
  async generateText(prompt: string, options?: any): Promise<string> {
    console.log(`🤖 Processing: ${prompt.substring(0, 60)}...`);
    await new Promise(resolve => setTimeout(resolve, 800)); // Realistic delay
    
    // Intent classification responses
    if (prompt.includes('intent classification') || prompt.includes('classify')) {
      if (prompt.includes('build') || prompt.includes('create') || prompt.includes('generate')) {
        return JSON.stringify({
          intent: 'generation',
          confidence: 0.95,
          reasoning: 'User wants to create/build something new based on action verbs in their request',
          shouldExecuteDirectly: prompt.includes('simple') || prompt.includes('basic'),
          shouldShowOptions: prompt.includes('complex') || prompt.includes('options')
        });
      } else if (prompt.includes('explain') || prompt.includes('how') || prompt.includes('what')) {
        return JSON.stringify({
          intent: 'explanation', 
          confidence: 0.88,
          reasoning: 'User is asking for explanation based on question words',
          shouldExecuteDirectly: false,
          shouldShowOptions: true
        });
      }
    }
    
    // Chat assistant responses
    if (prompt.includes('friendly') || prompt.includes('conversational')) {
      const responses = [
        "Hello! 👋 I'm excited to help you build something amazing today! What kind of project do you have in mind? I can help with websites, code review, documentation, or just chat about your ideas!",
        "Hi there! 🌟 I see you want to create something. That's awesome! Whether it's a sleek website, a powerful app, or just exploring ideas, I'm here to guide you through it. What's your vision?",
        "Hey! 🚀 Ready to build something incredible? I love helping people turn their ideas into reality. Tell me what you're thinking and let's make it happen together!"
      ];
      return responses[Math.floor(Math.random() * responses.length)];
    }
    
    // Website generation responses
    if (prompt.includes('website') || prompt.includes('HTML')) {
      return JSON.stringify({
        html: `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AI Generated Website</title>
    <style>
        body { font-family: 'Segoe UI', system-ui, sans-serif; margin: 0; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); }
        .container { max-width: 1200px; margin: 0 auto; padding: 2rem; color: white; }
        .hero { text-align: center; padding: 4rem 0; }
        .hero h1 { font-size: 3rem; margin-bottom: 1rem; }
        .features { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 2rem; margin-top: 3rem; }
        .feature { background: rgba(255,255,255,0.1); padding: 2rem; border-radius: 10px; backdrop-filter: blur(10px); }
    </style>
</head>
<body>
    <div class="container">
        <div class="hero">
            <h1>🚀 Welcome to Your AI-Generated Website!</h1>
            <p>This website was created by AI agents working together</p>
        </div>
        <div class="features">
            <div class="feature">
                <h3>🤖 AI-Powered</h3>
                <p>Built using intelligent agents that understand your needs</p>
            </div>
            <div class="feature">
                <h3>⚡ Lightning Fast</h3>
                <p>Optimized for performance and user experience</p>
            </div>
            <div class="feature">
                <h3>📱 Responsive</h3>
                <p>Works perfectly on all devices and screen sizes</p>
            </div>
        </div>
    </div>
</body>
</html>`,
        css: `/* Generated by AI - Modern, responsive styles */`,
        js: `console.log('🎉 AI-generated website loaded successfully!');`,
        metadata: { framework: 'vanilla', dependencies: [], aiGenerated: true }
      });
    }
    
    // Code review responses
    if (prompt.includes('code review') || prompt.includes('analyze code')) {
      return JSON.stringify({
        overallScore: 85,
        summary: 'Clean, well-structured code with modern practices. Some minor improvements suggested.',
        issues: [
          {
            type: 'suggestion',
            category: 'performance',
            line: 12,
            message: 'Consider using const instead of let for variables that don\'t change',
            suggestion: 'Replace let with const for immutable variables',
            severity: 'low',
            confidence: 0.9
          },
          {
            type: 'warning', 
            category: 'accessibility',
            line: 25,
            message: 'Missing alt attributes on images for screen readers',
            suggestion: 'Add descriptive alt text to all images',
            severity: 'medium',
            confidence: 0.95
          }
        ],
        strengths: [
          'Clean, readable code structure',
          'Good use of semantic HTML elements',
          'Proper error handling implemented',
          'Modern JavaScript features used appropriately'
        ],
        recommendations: [
          'Add unit tests for critical functions',
          'Implement proper loading states for async operations',
          'Consider adding TypeScript for better type safety'
        ],
        metrics: {
          linesOfCode: 127,
          complexity: 'medium',
          maintainabilityScore: 88,
          securityScore: 82,
          performanceScore: 79
        }
      });
    }
    
    return `✨ AI Response: ${prompt.substring(0, 100)}... [Generated by LiveDemoAIProvider]`;
  }

  async generateJSON(prompt: string, schema?: any): Promise<any> {
    const response = await this.generateText(prompt);
    try {
      return JSON.parse(response);
    } catch {
      return { message: response, generated: true };
    }
  }

  async chat(messages: any[]): Promise<string> {
    const lastMessage = messages[messages.length - 1];
    return this.generateText(lastMessage.content);
  }

  isConfigured(): boolean { return true; }
  getName(): string { return 'LiveDemoAIProvider'; }
  getVersion(): string { return '1.0.0'; }
}

// Enhanced Test Agents
class IntentClassificationDemo extends BaseAgent {
  constructor(provider: AIProvider) {
    super({
      id: 'intent-demo',
      name: 'Intent Classification Demo',
      description: 'Demonstrates intent classification capabilities',
      version: '1.0.0',
      enabled: true,
      priority: 1,
      timeout: 10000,
      retries: 2,
      dependencies: [],
      capabilities: ['intent-classification', 'routing']
    }, provider);
  }

  async execute(input: any): Promise<AgentResult<any>> {
    const prompt = `Classify the intent of this user message: "${input.message}"`;
    const response = await this.provider.generateJSON(prompt);
    return { success: true, data: response };
  }

  validate(input: any): boolean { return !!input.message; }
  getInputSchema(): any { return {}; }
  getOutputSchema(): any { return {}; }
}

class ChatAssistantDemo extends BaseAgent {
  constructor(provider: AIProvider) {
    super({
      id: 'chat-demo',
      name: 'Chat Assistant Demo',
      description: 'Demonstrates friendly AI conversation',
      version: '1.0.0',
      enabled: true,
      priority: 2,
      timeout: 10000,
      retries: 2,
      dependencies: [],
      capabilities: ['conversation', 'assistance']
    }, provider);
  }

  async execute(input: any): Promise<AgentResult<string>> {
    const prompt = `Respond in a friendly, helpful way to: "${input.message}"`;
    const response = await this.provider.generateText(prompt);
    return { success: true, data: response };
  }

  validate(input: any): boolean { return !!input.message; }
  getInputSchema(): any { return {}; }
  getOutputSchema(): any { return {}; }
}

class WebsiteGeneratorDemo extends BaseAgent {
  constructor(provider: AIProvider) {
    super({
      id: 'website-demo',
      name: 'Website Generator Demo', 
      description: 'Demonstrates website generation capabilities',
      version: '1.0.0',
      enabled: true,
      priority: 3,
      timeout: 15000,
      retries: 2,
      dependencies: [],
      capabilities: ['website-generation', 'html', 'css', 'javascript']
    }, provider);
  }

  async execute(input: any): Promise<AgentResult<any>> {
    const prompt = `Generate a complete website for: ${input.description}`;
    const response = await this.provider.generateJSON(prompt);
    return { success: true, data: response };
  }

  validate(input: any): boolean { return !!input.description; }
  getInputSchema(): any { return {}; }
  getOutputSchema(): any { return {}; }
}

class CodeReviewDemo extends BaseAgent {
  constructor(provider: AIProvider) {
    super({
      id: 'review-demo',
      name: 'Code Review Demo',
      description: 'Demonstrates code analysis capabilities',
      version: '1.0.0', 
      enabled: true,
      priority: 4,
      timeout: 12000,
      retries: 2,
      dependencies: [],
      capabilities: ['code-review', 'analysis', 'quality-check']
    }, provider);
  }

  async execute(input: any): Promise<AgentResult<any>> {
    const prompt = `Analyze this code for quality, security, and performance: ${input.code}`;
    const response = await this.provider.generateJSON(prompt);
    return { success: true, data: response };
  }

  validate(input: any): boolean { return !!input.code; }
  getInputSchema(): any { return {}; }
  getOutputSchema(): any { return {}; }
}

// Demo Functions
async function demonstrateAgentCapabilities() {
  console.log('🎯 Demonstrating Individual Agent Capabilities...\n');

  const provider = new LiveDemoAIProvider();
  const registry = new DefaultAgentRegistry();
  const manager = new AgentManager(provider, registry);
  
  // Register demo agents
  registry.register({
    config: {
      id: 'intent-demo',
      name: 'Intent Classification Demo',
      description: 'Smart intent detection',
      version: '1.0.0',
      enabled: true,
      priority: 1,
      timeout: 10000,
      retries: 2,
      dependencies: [],
      capabilities: ['intent-classification']
    },
    factory: (p) => new IntentClassificationDemo(p)
  });

  registry.register({
    config: {
      id: 'chat-demo', 
      name: 'Chat Assistant Demo',
      description: 'Friendly AI conversation',
      version: '1.0.0',
      enabled: true,
      priority: 2,
      timeout: 10000,
      retries: 2,
      dependencies: [],
      capabilities: ['conversation']
    },
    factory: (p) => new ChatAssistantDemo(p)
  });

  registry.register({
    config: {
      id: 'website-demo',
      name: 'Website Generator Demo',
      description: 'Complete website creation',
      version: '1.0.0',
      enabled: true,
      priority: 3,
      timeout: 15000,
      retries: 2,
      dependencies: [],
      capabilities: ['website-generation']
    },
    factory: (p) => new WebsiteGeneratorDemo(p)
  });

  registry.register({
    config: {
      id: 'review-demo',
      name: 'Code Review Demo', 
      description: 'Code quality analysis',
      version: '1.0.0',
      enabled: true,
      priority: 4,
      timeout: 12000,
      retries: 2,
      dependencies: [],
      capabilities: ['code-review']
    },
    factory: (p) => new CodeReviewDemo(p)
  });

  // Demo scenarios
  console.log('1️⃣ Intent Classification - Understanding User Requests:');
  const intentResult = await manager.executeAgent('intent-demo', {
    message: 'I want to build a modern e-commerce website with React'
  });
  console.log(`   🎯 Detected: ${intentResult.data?.intent} (${Math.round(intentResult.data?.confidence * 100)}% confident)`);
  console.log(`   💡 Reasoning: ${intentResult.data?.reasoning}`);

  console.log('\n2️⃣ Chat Assistant - Friendly AI Interaction:');
  const chatResult = await manager.executeAgent('chat-demo', {
    message: 'Hi! I need help choosing between React and Vue for my project'
  });
  console.log(`   🤖 Response: ${chatResult.data?.substring(0, 100)}...`);

  console.log('\n3️⃣ Website Generation - Creating Complete Websites:');
  const websiteResult = await manager.executeAgent('website-demo', {
    description: 'A portfolio website for a UI/UX designer with dark theme'
  });
  console.log(`   🌐 Generated: ${websiteResult.data?.html ? 'Complete HTML website' : 'Website structure'}`);
  console.log(`   📝 Length: ${websiteResult.data?.html?.length || 0} characters of HTML`);

  console.log('\n4️⃣ Code Review - Quality Analysis:');
  const reviewResult = await manager.executeAgent('review-demo', {
    code: `function calculateTotal(items) {
  let total = 0;
  for (const item of items) {
    total += item.price * item.quantity;
  }
  return total;
}`
  });
  console.log(`   📊 Quality Score: ${reviewResult.data?.overallScore}/100`);
  console.log(`   🔍 Issues Found: ${reviewResult.data?.issues?.length || 0}`);
  console.log(`   ✅ Strengths: ${reviewResult.data?.strengths?.length || 0} identified`);
}

async function demonstrateMultiAgentWorkflow() {
  console.log('\n🔄 Demonstrating Multi-Agent Workflow...\n');

  const provider = new LiveDemoAIProvider();
  const registry = new DefaultAgentRegistry();
  const manager = new AgentManager(provider, registry);
  const contextManager = new ContextManager();

  // Register agents
  [
    { id: 'intent-demo', factory: (p: AIProvider) => new IntentClassificationDemo(p) },
    { id: 'chat-demo', factory: (p: AIProvider) => new ChatAssistantDemo(p) },
    { id: 'website-demo', factory: (p: AIProvider) => new WebsiteGeneratorDemo(p) },
    { id: 'review-demo', factory: (p: AIProvider) => new CodeReviewDemo(p) }
  ].forEach(agent => {
    registry.register({
      config: {
        id: agent.id,
        name: `${agent.id} agent`,
        description: 'Demo agent',
        version: '1.0.0',
        enabled: true,
        priority: 1,
        timeout: 15000,
        retries: 2,
        dependencies: [],
        capabilities: [agent.id]
      },
      factory: agent.factory
    });
  });

  const userRequest = "I want to create a professional website for my design studio";
  console.log(`📝 User Request: "${userRequest}"`);

  // Step 1: Understand intent
  console.log('\n   Step 1: Understanding User Intent...');
  const context = await contextManager.createContext();
  const intentResult = await manager.executeAgent('intent-demo', { message: userRequest }, context);
  console.log(`   ✅ Intent: ${intentResult.data?.intent} (${Math.round(intentResult.data?.confidence * 100)}%)`);

  // Step 2: Generate website based on intent
  if (intentResult.data?.intent === 'generation') {
    console.log('\n   Step 2: Generating Website...');
    const websiteResult = await manager.executeAgent('website-demo', { 
      description: userRequest 
    }, context);
    console.log(`   ✅ Website Created: ${websiteResult.data?.html ? 'HTML structure ready' : 'Generation completed'}`);

    // Step 3: Review generated code
    if (websiteResult.data?.html) {
      console.log('\n   Step 3: Reviewing Code Quality...');
      const reviewResult = await manager.executeAgent('review-demo', {
        code: websiteResult.data.html
      }, context);
      console.log(`   ✅ Quality Review: ${reviewResult.data?.overallScore}/100 score`);
      
      // Step 4: Provide recommendations
      console.log('\n   Step 4: Providing Guidance...');
      const chatResult = await manager.executeAgent('chat-demo', {
        message: `The website has been generated with a quality score of ${reviewResult.data?.overallScore}/100. What are the next steps?`
      }, context);
      console.log(`   ✅ Guidance: ${chatResult.data?.substring(0, 120)}...`);
    }
  }

  console.log('\n   🎉 Multi-agent workflow completed successfully!');
}

async function demonstrateContextManagement() {
  console.log('\n💾 Demonstrating Context Management...\n');

  const contextManager = new ContextManager();
  
  // Create session
  const context = await contextManager.createContext(undefined, {
    userType: 'developer',
    projectType: 'e-commerce',
    experience: 'intermediate'
  });
  
  console.log(`   📋 Session Created: ${context.sessionId}`);
  
  // Store conversation state
  await contextManager.setVariable(context.sessionId, 'preferredFramework', 'React');
  await contextManager.setVariable(context.sessionId, 'budget', 'medium');
  await contextManager.setVariable(context.sessionId, 'timeline', '2 weeks');
  
  // Add messages
  await contextManager.addMessage(context.sessionId, {
    id: '1',
    agentId: 'user',
    type: 'input',
    content: 'I want to build an e-commerce site',
    timestamp: new Date()
  });
  
  await contextManager.addMessage(context.sessionId, {
    id: '2', 
    agentId: 'intent-demo',
    type: 'output',
    content: 'Generation intent detected',
    timestamp: new Date()
  });
  
  // Retrieve context
  const framework = await contextManager.getVariable(context.sessionId, 'preferredFramework');
  const messages = await contextManager.getMessages(context.sessionId);
  
  console.log(`   ⚙️  Stored Preference: ${framework}`);
  console.log(`   💬 Conversation History: ${messages.length} messages`);
  console.log(`   📊 Context Summary: ${await contextManager.summarizeContext(context.sessionId)}`);
}

// Main Demo
async function runLiveDemo() {
  console.log('🚀 AI Agents System - Live Demo');
  console.log('=' .repeat(50));
  console.log('This demo shows the AI agents working with realistic responses\n');
  
  try {
    await demonstrateAgentCapabilities();
    await demonstrateMultiAgentWorkflow();
    await demonstrateContextManagement();
    
    console.log('\n' + '=' .repeat(50));
    console.log('🎉 Live Demo Completed Successfully!');
    console.log('\n🌟 What You Just Saw:');
    console.log('   ✅ Intelligent intent classification');
    console.log('   ✅ AI-powered website generation');  
    console.log('   ✅ Automated code quality reviews');
    console.log('   ✅ Multi-agent workflow orchestration');
    console.log('   ✅ Persistent context management');
    console.log('   ✅ Event-driven agent coordination');
    console.log('\n🚀 Ready for Production:');
    console.log('   • Replace MockAIProvider with OpenAI/Anthropic/etc.');
    console.log('   • Integrate with your existing Express/Fastify server');
    console.log('   • Add real AI provider credentials');
    console.log('   • Deploy with full workflow capabilities');
    
  } catch (error) {
    console.error('\n❌ Demo failed:', error);
  }
}

if (require.main === module) {
  runLiveDemo();
}

export { runLiveDemo };