name: Tests

on:
  push:
    branches: [ main, production, feat-*, develop ]
  pull_request:
    branches: [ main, production ]

jobs:
  # Job 1: Basic tests (no API key required)
  basic-tests:
    name: Basic Tests (No API Key)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run basic validation tests
        run: npm run test:basic

      - name: Run reliability tests
        run: npm run test:reliability

  # Job 2: Agent tests (requires API key)
  agent-tests:
    name: Agent Tests (With API Key)
    runs-on: ubuntu-latest
    # Only run if API key secret is available
    if: ${{ secrets.OPENAI_API_KEY != '' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run orchestrator tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: npm run test:orchestrator

      - name: Run modification tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: npm run test:modifications

      - name: Run debugger tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: npm run test:debugger

  # Job 3: AutoGen tests (requires API key, slower)
  autogen-tests:
    name: AutoGen Tests (With API Key)
    runs-on: ubuntu-latest
    # Only run if API key secret is available
    if: ${{ secrets.OPENAI_API_KEY != '' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run reviewer agent tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: npm run test:reviewer

      - name: Run reflection loop tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: npm run test:reflection

  # Job 4: Integration tests (requires API key, longest)
  integration-tests:
    name: Integration Tests (With API Key)
    runs-on: ubuntu-latest
    # Only run on main branch or pull requests to main
    if: ${{ (github.ref == 'refs/heads/main' || github.base_ref == 'main') && secrets.OPENAI_API_KEY != '' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run integration tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: npm run test:integration
        timeout-minutes: 10

  # Job 5: Summary report
  test-summary:
    name: Test Summary
    runs-on: ubuntu-latest
    needs: [basic-tests, agent-tests, autogen-tests]
    if: always()

    steps:
      - name: Check test results
        run: |
          echo "Test Summary:"
          echo "✅ Basic tests: ${{ needs.basic-tests.result }}"
          echo "🤖 Agent tests: ${{ needs.agent-tests.result }}"
          echo "🔄 AutoGen tests: ${{ needs.autogen-tests.result }}"

      - name: Report status
        if: needs.basic-tests.result != 'success' || needs.agent-tests.result == 'failure' || needs.autogen-tests.result == 'failure'
        run: exit 1
